kf_vio_pnp_node:
  ros__parameters:
    vio_delay_sec: 0.0667 # seconds
    vio_delay_compensation: true

    vio_bias_rw_std: 0.005 # random walk std for position bias, unit (m/s per sqrt(s))
    vio_pos_std: 0.05
    vio_vel_std: 0.80
    pnp_pos_std: 0.03
    accel_noise_std: 0.05 # std for accelerometer noise for the process model, unit (m/s^2)

    # debug with mocap as pnp
    mocap_as_pnp: true
    mocap_mode: 'periodic' # 'periodic' or 'downsample'
    mocap_freq: 10.0 # hz, assume the full freq of mocap is 100 hz
    mocap_available_duration: 2.0 # seconds
    mocap_unavailable_duration: 10.0 # seconds

    # initial position for vio in pnp frame, unit (m)
    initial_pos_x: 0.085
    initial_pos_y: 0.060
    initial_pos_z: 0.0
    